AWSTemplateFormatVersion: "2010-09-09"
Description: "New EC2 instance"

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04fcd96153cb57194
      InstanceType: t2.micro
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      KeyName: cfn-key-1

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Cfn-SG
      GroupDescription: My new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

  NewElasicIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance