AWSTemplateFormatVersion: "2010-09-09"
Description: Template that uses mapping to fetch AMIs for EC2 instances

Parameters:
  MyKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Select an existing key pair from list

  Environments:
    Type: String
    AllowedValues:
      - Dev
      - Prod

Mappings:
  MyRegionMap:
    us-east-2:
      AMI: ami-04fcd96153cb57194
    us-east-1:
      AMI: ami-00514a528eadbc95b

  MyEnvironments:
    Dev:
      InstanceType: t2.micro
    Prod:
      InstanceType: t2.small

Resources:
  EnvEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [MyRegionMap,!Ref 'AWS::Region',AMI]
      KeyName: !Ref MyKeyName
      InstanceType: !FindInMap [MyEnvironments,!Ref Environments,InstanceType]